apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "interviewcoach.fullname" . }}
  labels:
    {{- include "interviewcoach.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "interviewcoach.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "interviewcoach.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        environment: {{ .environment }}
        team: {{ .team }}
        project: {{ .project }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "interviewcoach.fullname" . }}-openai
              key: OPENAI_API_KEY
        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}