{{- if .Values.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interviewcoach.fullname" . }}-openai
  labels:
    {{- include "interviewcoach.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.openai.apiKey }}
{{- end }}